---
title: "Critical Role Subtitles"
output: rmarkdown::github_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.path = "output/README_figs/"
)
```


# To Do:
  - Data cleaning: ADD splitting together [0,1] with https://docs.google.com/spreadsheets/d/1Zx1N0cQcd1fJadUwar7f2hJ2p61qoX7lctsVaIEa5uM/edit#gid=744793917
  - Initial Analysis: PENDING
  - Model Fitting:
  
## Data Cleaning:
```{r cleaning, eval=FALSE, warning=FALSE}
# run script
source("./scripts/data_cleaning.R", local = knitr::knit_global())

# Note: E031-2,E035-2,E082,E113-1,E113-2 have been run once through
# error fixing* with Subtitle editor** in Ubuntu 20.04. This is needed as
# the files contain formatting errors, which renders them unusable for the 
# following analysis. 
# The original files are included in the same folder and are named as follows:
# 'original_C1E031-1_FINAL.srt'
# * Tools -> Error checking -> Error -> Try to fix all 
# ** (install via 'sudo apt install subtitleeditor' on ubuntu)
```  

## Create Data for Visualization
```{r descriptive_analysis, eval=FALSE, warning=FALSE}
# run script
source("./scripts/data_descriptive_analysis.R", local = knitr::knit_global())
```  

## Descriptive Analysis:
```{r descriptive_analysis, eval=FALSE, warning=FALSE}
# run script
source("./scripts/descriptive_analysis.R", local = knitr::knit_global())
```  

## Machine Learning:
```{r descriptive_analysis, eval=FALSE, warning=FALSE}
# run script
source("./scripts/machine_learning.R", local = knitr::knit_global())
```  



## Explain Models
  - LIME package 
  - CARET

## Packages to look at:
  - parsnip
  - here
  - oxgen2
  - lintr
  - styler
  - speeling
  - usethis
  - Rstarters
  - project template
  - repv
  

- https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html